# Generated by Django 3.1.1 on 2020-09-08 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_navmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='navmenu',
            name='parent',
            field=models.BooleanField(default=False),
        ),
    ]
