# Generated by Django 3.1.1 on 2020-09-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_navmenu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navmenu',
            name='prent_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.navmenu'),
        ),
    ]
