# Generated by Django 3.1.1 on 2020-09-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200908_1858'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navmenu',
            options={'verbose_name_plural': 'navs'},
        ),
        migrations.AlterUniqueTogether(
            name='navmenu',
            unique_together={('slug',)},
        ),
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('primary', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='board.nav')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PrimaryNav',
            fields=[
            ],
            options={
                'verbose_name': 'Nav',
                'verbose_name_plural': 'Navs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.nav',),
        ),
        migrations.CreateModel(
            name='SubNav',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Nav',
                'verbose_name_plural': 'Sub Navs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('board.nav',),
        ),
    ]
